# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://MetaphoraStudios.github.io/DataImporters/"

git_url = "https://github.com/MetaphoraStudios/DataImporters/tree/main/"

def custom_doc_links(name): return None
