# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_version": "00_core.ipynb",
         "bump_version": "00_core.ipynb",
         "Dataset": "01_dataset.ipynb",
         "AUDIO_EXTENSIONS": "04_sources_core.ipynb",
         "Source": "04_sources_core.ipynb",
         "normalise_label": "04_sources_core.ipynb",
         "normalise_all_labels": "04_sources_core.ipynb",
         "get_footstep_type": "04_sources_core.ipynb",
         "get_filenames": "04_sources_core.ipynb",
         "get_hash": "04_sources_core.ipynb",
         "process": "04_sources_core.ipynb",
         "LENGTH_THRESHOLD": "05_source_space_divers_mini.ipynb",
         "SpaceDiversMini": "05_source_space_divers_mini.ipynb"}

modules = ["core.py",
           "dataset.py",
           "sources/core.py",
           "sources/space_divers_mini.py"]

doc_url = "https://MetaphoraStudios.github.io/DataImporters/"

git_url = "https://github.com/MetaphoraStudios/DataImporters/tree/main/"

def custom_doc_links(name): return None
