# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['load_version', 'bump_version']

# Cell
import os

def load_version(version_path: str = "version"):
    with open(version_path, "r") as f:
        return int(f.read())

# Cell

def bump_version(version_path: str = "version"):
    """Increments the version in the version file, by 1."""
    version = load_version(version_path)
    with open(version_path, "w") as f:
        f.write(str(version + 1))
        print("Version moved from {} to {}".format(version, version + 1))