# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/09_source_barefoot_metal_sonniss.ipynb (unless otherwise specified).


from __future__ import annotations


__all__ = ['BarefootMetalSonniss']

# Cell

#nbdev_comment from __future__ import annotations

from .core import *

import os

# Cell

class BarefootMetalSonniss(Source):
    @property
    def name(self) -> str:
        return "barefoot_metal_sonniss"

    def get_files(self, root_dir: str) -> list[tuple[str, str]]:
        return get_audio_filenames(root_dir)

    def get_category(self, path: str, filename: str) -> str:
        return "footsteps"

    def get_labels(self, path: str, filename: str) -> list[str]:
        labels = []

        filename = remove_extension(filename).split("-")[1]

        step_label = get_footstep_type(filename)
        if step_label is not None:
            filename = filename.lower().replace(" " + step_label, "")
            labels.append(step_label)

        labels.append(filename)
        return labels