# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_sources_core.ipynb (unless otherwise specified).

__all__ = ['Source']

# Cell

import pandas as pd

# Cell

class Source:
    def __init__(self, name: str):
        self.name = name