# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/10_source_custom_fsd.ipynb (unless otherwise specified).

__all__ = ['CustomFsd']

# Cell

from .core import *

import os
import pandas as pd

# Internal Cell

def _clean_category_name(category_name):
    return category_name.replace("+", " ").split("&")[0]

# Cell

class CustomFsd(Source):
    def preload(self, root_dir: str):
        metadata_path = os.path.join(root_dir, "metadata.csv")
        columns = ["id", "filename", "category", "tags"]
        self.metadata = pd.read_csv(metadata_path, header=None, names=columns)

    @property
    def name(self) -> str:
        return "custom_fsd"

    def get_files(self, root_dir: str) -> list[tuple[str, str]]:
        return get_filenames(root_dir)

    def get_category(self, path: str, filename: str) -> str:
        category = self.metadata.loc[self.metadata["filename"] == filename, "category"].values[0]
        return _clean_category_name(category)

    def get_labels(self, path: str, filename: str) -> list[str]:
        tags = self.metadata.loc[self.metadata["filename"] == filename, "tags"].values[0]
        return tags.split(",")