# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/07_source_footsteps_two_ppsfx_008.ipynb (unless otherwise specified).


from __future__ import annotations


__all__ = ['FootstepsTwoPpsfx']

# Cell

#nbdev_comment from __future__ import annotations

from .core import *
from .footsteps_one_ppsfx import FootstepsOnePpsfx

import os
import pandas as pd

# Cell

class FootstepsTwoPpsfx(FootstepsOnePpsfx):
    def preload(self, root_dir: str):
        metadata_path = os.path.join(root_dir,
            "Documents", "PPSFX008 - Footsteps Two Metadata.xls")
        self.extra_metadata = pd.read_excel(metadata_path)

    @property
    def name(self) -> str:
        return "footsteps_two_ppsfx_008"

    def get_files(self, root_dir: str) -> list[tuple[str, str]]:
        samples_dir = os.path.join(root_dir, "Audio")
        return get_audio_filenames(samples_dir)

    def get_category(self, path: str, filename: str) -> str:
        return "footsteps"

    def get_labels(self, path: str, filename: str) -> list[str]:
        # Replace Plain II with Plain
        filename = filename.replace("Plain II", "Plain")

        return super().get_labels(path, filename)

    def get_extra(self, path: str, filename: str) -> str:
        row = self.extra_metadata.loc[self.extra_metadata["Filename"] == remove_extension(filename)]
        return row["BWDescription"].values[0]